# Practical Question 1: Run Workflow on Every Push
# Scenario
# You have a Python project in GitHub. Every time someone pushes code to the main branch, GitHub Actions should:
# Checkout the code
# Print "Build Started"
# Display Python version
# Print "Build Completed"
# Expected Skills
# on: push
# actions/checkout
# run
# Multiple steps

name : my-first-workflow

on:
 push:
   branches:
    -main

jobs:
 first-job:
  runs-on: ubuntu-latest
   
  steps:
    - name : checkout-repository
      uses : actions/checkout@v4

    - name : build-started
      run  : echo "build started" 

    - name : display python version 
      run :  python --version

    - name: build completed
      run : echo "build completed"

